In [1]:
import pandas as pd
users = pd.read_csv("../data/Users.csv")
books = pd.read_csv("../data/Books.csv")
ratings = pd.read_csv("../data/Ratings.csv")

/tmp/ipykernel_189404/2632007961.py:3: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("../data/Books.csv")

In [2]:
books.info()

<class 'pandas.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  str
 1   Book-Title           271360 non-null  str
 2   Book-Author          271358 non-null  str
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  str
 5   Image-URL-S          271360 non-null  str
 6   Image-URL-M          271360 non-null  str
 7   Image-URL-L          271357 non-null  str
dtypes: object(1), str(7)
memory usage: 16.6+ MB

In [3]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  str
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 6.4 MB

In [4]:
ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  str
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), str(1)
memory usage: 26.3 MB

In [6]:
nup_books = books.drop_duplicates("Book-Title")
nup_books.info()

<class 'pandas.DataFrame'>
Index: 242135 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 242135 non-null  str
 1   Book-Title           242135 non-null  str
 2   Book-Author          242133 non-null  str
 3   Year-Of-Publication  242135 non-null  object
 4   Publisher            242134 non-null  str
 5   Image-URL-S          242135 non-null  str
 6   Image-URL-M          242135 non-null  str
 7   Image-URL-L          242132 non-null  str
dtypes: object(1), str(7)
memory usage: 16.6+ MB

In [8]:
ratings_with_name = ratings.merge(nup_books, on="ISBN")
ratings_with_name.drop(["ISBN", "Image-URL-S", "Image-URL-M", "Image-URL-L", "Publisher"], axis=1, inplace=True)
ratings_with_name.head()

,User-ID,Book-Rating,Book-Title,Book-Author,Year-Of-Publication
0,276725,0,Flesh Tones: A Novel,M. J. Rose,2002
1,276729,3,Help!: Level 1,Philip Prowse,1999
2,276729,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001
3,276746,0,Lightning,Dean R. Koontz,1996
4,276746,0,Manhattan Hunt Club,JOHN SAUL,2002

In [10]:
len(ratings_with_name["User-ID"].unique())

83910

In [11]:
ratings_with_name.info()

<class 'pandas.DataFrame'>
RangeIndex: 883079 entries, 0 to 883078
Data columns (total 5 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   User-ID              883079 non-null  int64
 1   Book-Rating          883079 non-null  int64
 2   Book-Title           883079 non-null  str
 3   Book-Author          883077 non-null  str
 4   Year-Of-Publication  883079 non-null  object
dtypes: int64(2), object(1), str(2)
memory usage: 33.7+ MB

In [12]:
ratings_with_name.dropna(inplace=True)
ratings_with_name.info()

<class 'pandas.DataFrame'>
Index: 883077 entries, 0 to 883078
Data columns (total 5 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   User-ID              883077 non-null  int64
 1   Book-Rating          883077 non-null  int64
 2   Book-Title           883077 non-null  str
 3   Book-Author          883077 non-null  str
 4   Year-Of-Publication  883077 non-null  object
dtypes: int64(2), object(1), str(2)
memory usage: 40.4+ MB

In [14]:
x = ratings_with_name.groupby("User-ID").count()["Book-Rating"] > 100
expert_users = x[x].index

In [15]:
filtered_user_ratings = ratings_with_name[ratings_with_name["User-ID"].isin(expert_users)]

y = filtered_user_ratings.groupby("Book-Title").count()["Book-Rating"] > 50
famous_books = y[y].index

famous_ratings = filtered_user_ratings[filtered_user_ratings["Book-Title"].isin(famous_books)]

In [18]:
design_matrix = famous_ratings.pivot_table(index="Book-Title", columns="User-ID", values="Book-Rating")

In [19]:
design_matrix.head()

User-ID,254,507,882,1424,1435,1733,1903,2033,2110,2276,...,274808,275020,275970,276680,277427,277478,277639,278137,278188,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
design_matrix.fillna(0, inplace=True)

User-ID,254,507,882,1424,1435,1733,1903,2033,2110,2276,...,274808,275020,275970,276680,277427,277478,277639,278137,278188,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
design_matrix.describe()

User-ID,254,507,882,1424,1435,1733,1903,2033,2110,2276,...,274808,275020,275970,276680,277427,277478,277639,278137,278188,278418
count,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.0,603.000000,603.000000,603.000000,...,603.000000,603.000000,603.000000,603.000000,603.000000,603.0,603.000000,603.000000,603.000000,603.000000
mean,0.159204,0.051410,0.117745,0.046434,0.102819,0.081260,0.0,0.077944,0.036484,0.121061,...,0.102819,0.026534,0.099502,0.101161,0.203980,0.0,0.076285,0.053068,0.054726,0.071310
std,1.173288,0.638476,0.997206,0.571615,0.875682,0.824277,0.0,0.795895,0.536380,1.016608,...,0.953770,0.463941,0.931214,0.874927,1.333139,0.0,0.767369,0.652496,0.617026,0.719835
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
max,10.000000,10.000000,10.000000,8.000000,10.000000,10.000000,0.0,9.000000,10.000000,10.000000,...,10.000000,9.000000,10.000000,8.000000,10.000000,0.0,9.000000,9.000000,9.000000,8.000000

In [23]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

scaler = StandardScaler()
design_matrix_scaled = scaler.fit_transform(design_matrix)
design_matrix_scaled

array([[ 7.54131454, -0.08058611, -0.1181726 , ..., -0.08139833,
        -0.08876743, -0.09914679],
       [-0.13580308, -0.08058611, -0.1181726 , ..., -0.08139833,
        -0.08876743, -0.09914679],
       [-0.13580308, -0.08058611, -0.1181726 , ..., -0.08139833,
        -0.08876743, -0.09914679],
       ...,
       [-0.13580308, -0.08058611, -0.1181726 , ..., -0.08139833,
        -0.08876743, -0.09914679],
       [-0.13580308, -0.08058611, -0.1181726 , ..., -0.08139833,
        -0.08876743, -0.09914679],
       [-0.13580308, -0.08058611, -0.1181726 , ..., -0.08139833,
        -0.08876743, -0.09914679]], shape=(603, 1388))

In [24]:
similarity_score = cosine_similarity(design_matrix_scaled)
similarity_score

array([[ 1.        , -0.01888288, -0.02269722, ...,  0.01315243,
        -0.02208608, -0.02261118],
       [-0.01888288,  1.        ,  0.03596181, ..., -0.0227191 ,
        -0.03080347,  0.10328814],
       [-0.02269722,  0.03596181,  1.        , ..., -0.01495746,
        -0.01101762, -0.0212155 ],
       ...,
       [ 0.01315243, -0.0227191 , -0.01495746, ...,  1.        ,
        -0.0046991 , -0.01365949],
       [-0.02208608, -0.03080347, -0.01101762, ..., -0.0046991 ,
         1.        ,  0.01005596],
       [-0.02261118,  0.10328814, -0.0212155 , ..., -0.01365949,
         0.01005596,  1.        ]], shape=(603, 603))

In [25]:
import numpy as np

def recommend(book_name):
    index = np.where(design_matrix.index==book_name)[0][0]
    similar_books = sorted(list(enumerate(similarity_score[index])), key=lambda x: x[1], reverse=True)[1:6]
    data = []

    for index, similarity in similar_books:
        item = []
        temp_df = nup_books[nup_books["Book-Title"]==design_matrix.index[index]]
        item.extend(temp_df["Book-Title"].values)
        item.extend(temp_df["Book-Author"].values)
        data.append(item)
    return data

In [26]:
recommend("The Hot Zone")

[['Stanislaski Sisters', 'Nora Roberts'],
 ['Invasion', 'Robin Cook'],
 ['Acceptable Risk', 'Robin Cook'],
 ['The House on Mango Street (Vintage Contemporaries)', 'SANDRA CISNEROS'],
 ['The Body Farm', 'Patricia Daniels Cornwell']]

In [30]:
from sklearn.neighbors import KNeighborsTransformer
k= 5

model = KNeighborsTransformer(n_neighbors=k, mode="distance", metric="cosine")

transform = model.fit_transform(design_matrix_scaled)

book_title= "The Hot Zone"
book_index = np.where(design_matrix.index==book_title)[0][0]
csr = transform[book_index]

print(csr)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (1, 603)>
  Coords	Values
  (0, 461)	0.0
  (0, 375)	0.868881356198543
  (0, 222)	0.875740278257931
  (0, 29)	0.8855963509738889
  (0, 466)	0.8960356701342925
  (0, 402)	0.8993252095929694

In [31]:
for row in range(csr.shape[0]):
    start_index = csr.indptr[row] + 1
    end_index = csr.indptr[row + 1]
    for index in range(start_index, end_index):
        value = csr.data[index]
        column= csr.indices[index]
        print(f"{nup_books[nup_books["Book-Title"]==design_matrix.index[column]][["Book-Title", "Book-Author"]].values.flatten()}")

['Stanislaski Sisters' 'Nora Roberts']
['Invasion' 'Robin Cook']
['Acceptable Risk' 'Robin Cook']
['The House on Mango Street (Vintage Contemporaries)' 'SANDRA CISNEROS']
['The Body Farm' 'Patricia Daniels Cornwell']